image: WMF 5
install:
- ps: Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force -Verbose
- ps: Install-Module -Name Pester; Import-Module -Name Pester
build_script:
- ps: Invoke-Pester